version: "3"

services:
  nodeosd:
    build:
      context: .
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --delete-all-blocks --contracts-console --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    restart: always
    networks:
      - eva-api_eva-containers-network
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./multindex:/opt/eosio/bin/data-dir/multindex
      - ./js:/opt/eosio/bin/data-dir/js

  keosd:
    image: eosio/eos-dev:v1.0.4
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8900
    hostname: keosd
    restart: always
    networks:
      - eva-api_eva-containers-network
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true

networks:
  eva-api_eva-containers-network:
     external: true
